version: "3.3"

services:

  telegram: &base_app
    build: .
    volumes:
    - ./:/code/
    depends_on:
    - pg
    environment:
    - DB_NAME=wordknow
    - DB_USER=user
    - DB_PASSWORD=pass
    - DB_HOST=pg
    command: python manage.py telegram
    networks:
      - wordknow-net

  telegram_tasks:
    <<: *base_app
    command: python manage.py telegram_tasks

  server:
    <<: *base_app
    ports:
    - "9900:8000"
    command: python manage.py runserver 0.0.0.0:8000

  pg:
    image: postgres
    environment:
    - POSTGRES_PASSWORD=pass
    - POSTGRES_USER=user
    - POSTGRES_DB=wordknow
    networks:
    - wordknow-net
    volumes:
    - ./.pg:/var/lib/postgresql/data/
#    - wordknow-database:/var/lib/postgresql/data # it's used for increasing speed app

networks:
  wordknow-net:
    name: wordknow-net
    driver: bridge
