# Generated by Django 2.0.3 on 2018-03-27 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LearningStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_not_guess', models.IntegerField(default=0)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('count_words', models.IntegerField(default=5)),
                ('repetition_notified', models.DateTimeField(null=True, verbose_name='Когда оповещали о повторении слов')),
            ],
            options={
                'verbose_name': 'Статус пользователя повторения/изучения слов',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=100, verbose_name='ID чата в телеграме')),
                ('username', models.CharField(max_length=100, verbose_name='ID чата в телеграме')),
                ('status', models.CharField(choices=[('free', 'в свободном плавании'), ('learning', 'изучает новые слова'), ('learning_status', 'повторяет слова')], default='free', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=256)),
                ('translate', models.CharField(max_length=256)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WordStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_repetition_time', models.DateTimeField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('count_repetitions', models.IntegerField(default=0)),
                ('number_not_guess', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learned_words', to='app.User')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learned_words', to='app.Word')),
            ],
            options={
                'verbose_name': 'Статус изучения слова',
                'ordering': ('id',),
            },
        ),
        migrations.AddField(
            model_name='learningstatus',
            name='learn_word',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Word', verbose_name='На этом слове остановились изучать'),
        ),
        migrations.AddField(
            model_name='learningstatus',
            name='repeat_words',
            field=models.ManyToManyField(to='app.WordStatus'),
        ),
        migrations.AddField(
            model_name='learningstatus',
            name='repetition_word_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_repetition', to='app.WordStatus', verbose_name='На этом слове остановились повторять'),
        ),
        migrations.AddField(
            model_name='learningstatus',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.User'),
        ),
    ]
