# Generated by Django 2.0.3 on 2018-09-13 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180405_2154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learningstatus',
            name='number_not_guess',
        ),
        migrations.AddField(
            model_name='word',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.User', verbose_name='Cлово пользователя'),
        ),
        migrations.AlterField(
            model_name='learningstatus',
            name='count_words',
            field=models.IntegerField(default=5, verbose_name='Количество слов, которые пользователь будет учить за раз'),
        ),
        migrations.AlterField(
            model_name='wordstatus',
            name='count_repetitions',
            field=models.IntegerField(default=0, verbose_name='Количество повторений слова'),
        ),
        migrations.AlterField(
            model_name='wordstatus',
            name='number_not_guess',
            field=models.IntegerField(default=0, verbose_name='Сколько раз не угадал слово'),
        ),
        migrations.AlterField(
            model_name='wordstatus',
            name='start_repetition_time',
            field=models.DateTimeField(null=True, verbose_name='Время когда нужно будет повторить слово'),
        ),
    ]
