# Generated by Django 2.0.3 on 2018-09-17 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180913_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auth_code',
            field=models.CharField(default='', help_text='Высылается в telegram при попытке авторизоваться', max_length=10, verbose_name='Код для авторизации'),
        ),
        migrations.AddField(
            model_name='user',
            name='auth_token',
            field=models.UUIDField(null=True),
        ),
    ]
