# Generated by Django 2.0.3 on 2018-09-18 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20180917_0516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='auth_code',
            field=models.CharField(help_text='Высылается в telegram при попытке авторизоваться', max_length=10, null=True, verbose_name='Код для авторизации'),
        ),
    ]
