# Generated by Django 2.2.3 on 2019-08-05 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20180918_0618'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wordstatus',
            unique_together={('user', 'word')},
        ),
    ]
