# Generated by Django 2.2.3 on 2019-08-05 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20190805_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('free', 'в свободном плавании'), ('learning', 'изучает новые слова'), ('repetition', 'повторяет слова')], default='free', max_length=50),
        ),
    ]
