# Generated by Django 2.2.4 on 2019-08-22 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20190805_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='phrase',
            field=models.CharField(blank=True, max_length=256, verbose_name='Текст для лучшего запоминания'),
        ),
        migrations.AlterField(
            model_name='wordstatus',
            name='start_repetition_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время когда нужно будет повторить слово'),
        ),
    ]
