# Generated by Django 2.0.3 on 2018-03-26 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='learningstatus',
            options={'verbose_name': 'Статус пользователя повторения/изучения слов'},
        ),
        migrations.AddField(
            model_name='learningstatus',
            name='repetition_notified',
            field=models.DateTimeField(null=True, verbose_name='Когда оповещали о повторении слов'),
        ),
    ]
